# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f603e2401fc7805838f73c4e58bf547c7d475c1344679a16247f810c3f0efdbc2967bfb6368ab31ea6d771034d7c839bf7fe54da0da1691793115df65d5f4d1

test:
  secret_key_base: 1426c11e4b5794d21038d96e7884489de459d4dc63ab1281c55bb7970228a1f53f48f57914148a7d4b2f7334e3c2f648139ef0adf7edddb9ebda67f92b61b663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
